# Generated by Django 3.2.8 on 2021-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=20)),
                ('song_genre', models.CharField(max_length=15)),
            ],
        ),
    ]
